"""empty message

Revision ID: 1f6b49789f04
Revises: cb41dc0ea0ca
Create Date: 2019-02-23 17:19:44.332500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f6b49789f04'
down_revision = 'cb41dc0ea0ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameItem', sa.Column('Available', sa.Boolean(), nullable=False))
    op.alter_column('GameItem', 'MembersOnly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('GameItem', 'MembersOnly',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.drop_column('GameItem', 'Available')
    # ### end Alembic commands ###
