"""empty message

Revision ID: 2638498c9681
Revises: eebc31ce9d27
Create Date: 2020-05-02 09:15:05.315107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2638498c9681'
down_revision = 'eebc31ce9d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameItem', sa.Column('IconId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GameItem', 'IconId')
    # ### end Alembic commands ###
