"""empty message

Revision ID: 42cfd964364e
Revises: 32eb848c4612
Create Date: 2018-12-12 15:34:34.800793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42cfd964364e'
down_revision = '32eb848c4612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('GameTicket', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'GameTicket')
    # ### end Alembic commands ###
