"""empty message

Revision ID: 4370cf57404e
Revises: a48b2eaea95d
Create Date: 2018-12-16 18:15:02.121573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4370cf57404e'
down_revision = 'a48b2eaea95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameItem', sa.Column('Layered', sa.Enum('Y', 'N', name='singleenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GameItem', 'Layered')
    # ### end Alembic commands ###
