"""empty message

Revision ID: 4c687afef031
Revises: 8255b4c07c88
Create Date: 2018-11-17 21:56:11.087485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c687afef031'
down_revision = '8255b4c07c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Colors', 'Channel1',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Colors', 'Channel2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Colors', 'Channel3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Colors', 'Channel4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('Colors', 'ColorTable',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Colors', 'ColorTable',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('Colors', 'Channel4',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Colors', 'Channel3',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Colors', 'Channel2',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('Colors', 'Channel1',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
