"""empty message

Revision ID: 4c7a770d6261
Revises: 5a953c0c085f
Create Date: 2018-11-20 11:56:42.748896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7a770d6261'
down_revision = '5a953c0c085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GameItem',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.Enum('Clothing', 'Hair', 'Skin', 'Quest', 'Collectible', 'Pet', name='itemtype'), nullable=False),
    sa.Column('ItemName', sa.String(length=28), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.Column('Cost', sa.Integer(), nullable=True),
    sa.Column('Sale', sa.Integer(), nullable=True),
    sa.Column('MembersOnly', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GameItem')
    # ### end Alembic commands ###
