"""empty message

Revision ID: 4eb7046f053d
Revises: 7041b67282dc
Create Date: 2018-11-19 10:07:01.271100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eb7046f053d'
down_revision = '7041b67282dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Colors', 'ColorSet',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.Enum('Item', 'Hair', 'Skin', name='colorsets'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Colors', 'ColorSet',
               existing_type=sa.Enum('Item', 'Hair', 'Skin', name='colorsets'),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
