"""empty message

Revision ID: 5a953c0c085f
Revises: 07b53dd6429d
Create Date: 2018-11-20 11:12:23.671095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a953c0c085f'
down_revision = '07b53dd6429d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Colors', sa.Column('ItemType', sa.Enum('Clothing', 'Hair', 'Skin', 'Quest', 'Collectible', name='itemtype'), nullable=False))
    op.drop_column('Colors', 'ColorSet')
    op.add_column('User', sa.Column('Appearance', sa.String(length=72), nullable=False))
    op.alter_column('User', 'Email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('User', 'Password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('User', 'Username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'Username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.alter_column('User', 'Password',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('User', 'Email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('User', 'Appearance')
    op.add_column('Colors', sa.Column('ColorSet', mysql.ENUM('Item', 'Hair', 'Skin'), nullable=False))
    op.drop_column('Colors', 'ItemType')
    # ### end Alembic commands ###
