"""empty message

Revision ID: 8255b4c07c88
Revises: 
Create Date: 2018-11-17 21:53:21.361104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8255b4c07c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Colors',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ColorTable', sa.String(length=16), nullable=True),
    sa.Column('Channel1', sa.Integer(), nullable=True),
    sa.Column('Channel2', sa.Integer(), nullable=True),
    sa.Column('Channel3', sa.Integer(), nullable=True),
    sa.Column('Channel4', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Colors')
    # ### end Alembic commands ###
