"""empty message

Revision ID: 89b16f35a3d8
Revises: 363bb39fcf9a
Create Date: 2018-11-14 19:16:15.736237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b16f35a3d8'
down_revision = '363bb39fcf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=16), nullable=True),
    sa.Column('Password', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('UserId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('User')
    # ### end Alembic commands ###
