"""empty message

Revision ID: 94693ddc1580
Revises: 4c687afef031
Create Date: 2018-11-18 09:21:03.758505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94693ddc1580'
down_revision = '4c687afef031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Colors', sa.Column('ColorSet', sa.String(length=16), nullable=False))
    op.drop_column('Colors', 'ColorTable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Colors', sa.Column('ColorTable', mysql.VARCHAR(length=16), nullable=False))
    op.drop_column('Colors', 'ColorSet')
    # ### end Alembic commands ###
