"""empty message

Revision ID: a48b2eaea95d
Revises: 8041f33acc52
Create Date: 2018-12-16 18:14:35.941762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a48b2eaea95d'
down_revision = '8041f33acc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GameItem', 'Layered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GameItem', sa.Column('Layered', mysql.ENUM('T', 'F'), nullable=False))
    # ### end Alembic commands ###
