"""empty message

Revision ID: b4469d1f688d
Revises: 4370cf57404e
Create Date: 2018-12-17 11:52:38.553932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4469d1f688d'
down_revision = '4370cf57404e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BetaTickets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SerialKey', sa.String(length=14), nullable=False),
    sa.Column('Issued', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BetaTickets')
    # ### end Alembic commands ###
