"""empty message

Revision ID: cb41dc0ea0ca
Revises: b4469d1f688d
Create Date: 2018-12-19 16:54:10.601540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb41dc0ea0ca'
down_revision = 'b4469d1f688d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Color',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.Enum('Clothing', 'Hair', 'Skin', 'Quest', 'Collectible', 'Pet', 'Food', name='itemtype'), nullable=False),
    sa.Column('Channel1', sa.BigInteger(), nullable=False),
    sa.Column('Channel2', sa.BigInteger(), nullable=False),
    sa.Column('Channel3', sa.BigInteger(), nullable=False),
    sa.Column('Channel4', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.drop_table('Colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Colors',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Channel1', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Channel2', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Channel3', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Channel4', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('ItemType', mysql.ENUM('Clothing', 'Hair', 'Skin', 'Quest', 'Collectible'), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('Color')
    # ### end Alembic commands ###
