"""empty message

Revision ID: dafacab1daa1
Revises: 1f6b49789f04
Create Date: 2019-04-26 10:11:54.812695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafacab1daa1'
down_revision = '1f6b49789f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Inventory',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('GameItemId', sa.Integer(), nullable=True),
    sa.Column('ColorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ColorId'], ['Color.Id'], ),
    sa.ForeignKeyConstraint(['GameItemId'], ['GameItem.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inventory')
    # ### end Alembic commands ###
