"""empty message

Revision ID: eebc31ce9d27
Revises: 
Create Date: 2020-04-27 11:27:51.709008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebc31ce9d27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BetaTickets',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('SerialKey', sa.String(length=14), nullable=False),
    sa.Column('Issued', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Color',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.Enum('Clothing', 'Body', 'Shoes', 'Pants', 'Shirt', 'Hat', 'Face', 'Hair', 'Glasses', 'Quest', 'Collectible', 'Pet', 'Food', 'Apartment', name='itemtype'), nullable=False),
    sa.Column('Channel1', sa.BigInteger(), nullable=False),
    sa.Column('Channel2', sa.BigInteger(), nullable=False),
    sa.Column('Channel3', sa.BigInteger(), nullable=False),
    sa.Column('Channel4', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('GameItem',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('ItemType', sa.Enum('Clothing', 'Body', 'Shoes', 'Pants', 'Shirt', 'Hat', 'Face', 'Hair', 'Glasses', 'Quest', 'Collectible', 'Pet', 'Food', 'Apartment', name='itemtype'), nullable=False),
    sa.Column('ItemName', sa.String(length=28), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=False),
    sa.Column('Layered', sa.Enum('N', 'Y', name='singleenum'), nullable=False),
    sa.Column('Cost', sa.Integer(), nullable=True),
    sa.Column('Sale', sa.Integer(), nullable=True),
    sa.Column('Available', sa.Boolean(), nullable=False),
    sa.Column('MembersOnly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('User',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=16), nullable=False),
    sa.Column('Password', sa.String(length=64), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Appearance', sa.String(length=72), nullable=False),
    sa.Column('GameTicket', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Inventory',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('UserId', sa.Integer(), nullable=True),
    sa.Column('GameItemId', sa.Integer(), nullable=True),
    sa.Column('ColorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ColorId'], ['Color.Id'], ),
    sa.ForeignKeyConstraint(['GameItemId'], ['GameItem.Id'], ),
    sa.ForeignKeyConstraint(['UserId'], ['User.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Inventory')
    op.drop_table('User')
    op.drop_table('GameItem')
    op.drop_table('Color')
    op.drop_table('BetaTickets')
    # ### end Alembic commands ###
